'use client'

import './globals.css'
import { Template } from '@/components/Template'
import { QueryClient, QueryClientProvider } from 'react-query'

import React, { useEffect, useState } from 'react'
import { Providers } from '@/core/redux/provider'
import { useTheme } from '@/shared/hooks/useTheme'

// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  const queryClient = new QueryClient()
  const { getLocalStorage } = useTheme()
  const [theme, setTheme] = useState<'dark' | 'light'>('light')

  useEffect(() => {
    setTheme(getLocalStorage())
  }, [])

  return (
    <html className={theme}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`font-montserrat flex h-screen flex-row items-center justify-end gap-7 bg-gray-blue text-zinc-600 selection:bg-teal-600 selection:text-white dark:bg-zinc-800 dark:text-zinc-100 lg:p-7`}
      >
        <QueryClientProvider client={queryClient}>
          <Providers>
            <Template.Root>{children}</Template.Root>
          </Providers>
        </QueryClientProvider>
      </body>
    </html>
  )
}
